### ISSUE TITLE
Non-copy-constructibility tests fail

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/strf#17]
See also issue #16.

The following tests are failing:

    bool test1 = ! std::is_copy_constructible
        <strf::constrained_fpe<is_64, facet<0, enable_only_move>>>
        ::value;

    bool test3 = ! std::is_copy_constructible
        <strf::facets_pack<facet<0, enable_only_move>>>
        ::value;

    bool test5 =  ! std::is_copy_constructible
        < strf::facets_pack
             < strf::constrained_fpe
                 < is_64, facet<0, enable_only_move> >>>
        :: value;

    bool test7 = ! std::is_move_constructible
        < strf::facets_pack<facet<0, disable_copy_and_move>> >
        ::value;

It's not so clear to me why that's happening, though. Perhaps @robhz786  can help?

**Comment by robhz786** [comment]
If you declare a copy constructor, then `std::is_copy_constructible<your_class>::value` is `true` unconditionally, even if the copy constructor fails to compile. And I don't think it is possible to use any sfinae trick here. The only solution seem to defaulting the constructors ( either by omitting the declaration or by using `=default;` ). If this is not possible, I think the issue is unsolvable.

https://akrzemi1.wordpress.com/2015/03/02/a-conditional-copy-constructor/

**Comment by eyalroz** [comment]
@robhz786 : But are we talking about declarations I added?

Oh, I remember there were someplaces I had to replace `= default;`  with manually writing a default ctor, to make it `STRF_HD`. Maybe that's the cause here?

**Comment by robhz786** [comment]
@eyalroz Yes, that's the cause.
I created a pull request now. Take a look: https://github.com/eyalroz/strf/pull/18
Question: What happens if we declare the copy and move constructors with `= default;` but without `STRF_HD` ?

**Comment by robhz786** [comment]
I created a pull request now. Take a look.

**Comment by eyalroz** [comment]
All tests now pass.
